# services.py's messages
BANK_DETAIL_ADDED = 'Bank detail has been added...'
ATM_ADDRESS_ALREADY_EXISTED = 'At this address Bank has already Atm'
NEW_ATM_ADDED = 'New Atm has been added!...'
ATM_DELETED = 'Atm Deleted Successfully!'
ATM_DOES_NOT_EXIST = 'Atm does not exist!'
ATM_DATA_UPDATED = 'Atm has been updated!...'
BRANCH_DOES_NOT_EXIST = 'Branch does not exist!'
BRANCH_NAME_TAKEN = 'This branch name is already taken Kindly choose different one'
BRANCH_ADDRESS_ALREADY_EXIST = 'Bank has already branch at this at address!'
BRANCH_ADDED = 'New Branch has been added!...'
BRANCH_DELETED = 'Branch Deleted Successfully!'
BRANCH_DATA_UPDATED = 'Branch data has been updated!...'
