"""transaction_id added in otpbymail table

Revision ID: 90d2278ccdbf
Revises: 5c07915de1c0
Create Date: 2022-08-25 15:58:35.732360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d2278ccdbf'
down_revision = '5c07915de1c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_by_mail', sa.Column('transaction_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'otp_by_mail', 'transactions', ['transaction_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'otp_by_mail', type_='foreignkey')
    op.drop_column('otp_by_mail', 'transaction_id')
    # ### end Alembic commands ###
